src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz',
        2 => 'Fuel',
        3 => 'Charbon',
        4 => 'Autre'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * @Assert\Image(
     *      mimeTypes="image/jpeg"
     * )
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     * @var string|null
     */
    private $filename;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 10,
     *      max = 500,
     *      notInRangeMessage = "You must be between {{ min }}cm and {{ max }}m²",
     * )
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sold = false;

    public function __construct() {
        $this->created_at = new \DateTimeImmutable();
        $this->options = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     * @var datetime|null
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="property")
     */
    private $images;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, ',', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * Get nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @return  File|null
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set nOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @param File|UploadedFile|null $imageFile
     *
     * @return  self
     */ 
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            if($imageFile instanceof UploadedFile) {
                $this->updated_at = new \DateTime();
            }
        }

        return $this;
    }

    /**
     * Get the value of filename
     *
     * @return  string|null
     */ 
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set the value of filename
     *
     * @param  string|null  $filename
     *
     * @return  self
     */ 
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setProperty($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProperty() === $this) {
                $image->setProperty(null);
            }
        }

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    public function getChoices(): array
    {
        $choices = Property::HEAT;
        $output = [];

        foreach ($choices as $key => $value) {
            $output[$value] = $key;
        }

        return $output;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * 
 */
class PropertyController extends AbstractController
{
    private $repository;
    private $request;

    /**
     * Constructeur
     */
    public function __construct(PropertyRepository $repository )
    {
        $this->repository = $repository;
    }
   
    /**
     * @Route("/biens", name="property.index")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);


        // Récupération de tous les biens dans la base.
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12 /*limit per page*/
        );

        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[0-9a-z\-]*"})
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification) : Response
    {

        if($property->getSlug() !== $slug) 
        {
            return $this->redirectToRoute(
                'property.show', 
                [
                    'id' => $property->getId(),
                    'slug' => $property->getSlug()
                ], 
                301
            );
        }

        $contact = new Contact();
        $contact->setProperty($property);

        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);

            $this->addFlash('success', 'Votre message a bien té envoyé.');

            
            return $this->redirectToRoute(
                'property.show', 
                [
                    'id' => $property->getId(),
                    'slug' => $property->getSlug()
                ]
            );       
        }

        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()
            ]
        );
    }
}

templates/property/_carousel.html.twig
<div id="carouselControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
  {#{% for image in property.images %}#}
    <div class="carousel-item active">
      <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" class="d-block w-100" style="width: 100%; height: auto">
    </div>      
  {#{% endfor %}#}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

templates/property/_property.html.twig
<div class="card mb-4" style="width: 18rem;">
    {% if property.filename %}
    <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" class="card-img-top" style="width: 100%; height: auto">
    {% else %}
    <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" class="card-img-top" style="width: 100%; height: auto">        
    {% endif %}

    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {'id': property.id, 'slug': property.slug}) }}">{{ property.title }}</a>
        </h5>
        <!--p class="card-text">{{ property.description | nl2br}}</p-->
        <p class="card-text">{{ property.surface }}m² - {{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem">{{ property.formattedPrice }} €</div>
    </div>
</div>                

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Biens{% endblock %}

{% block body %}

    <div class="container-fluid bg-light mt-4">
        <div class="container">
            {{ form_start(form) }}
                <div class="row g-3 align-items-end">
                    <div class="col mt-4 mb-4">
                        {{ form_row(form.minSurface) }}
                    </div>                       
                    <div class="col mt-4 mb-4">
                        {{ form_row(form.maxPrice) }}
                    </div>                    
                    <div class="col mt-4 mb-4">
                        {{ form_row(form.options) }}
                    </div>                    
                    <div class="col mt-4 mb-4">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>                    
                </div>
            {{ form_rest(form) }}
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4 text-center">
        <h1>Voir tous nos Biens</h1>
        <div class="row">
            {% for property in properties %}
            <div class="col-md-4">
                {% include "property/_property.html.twig" %}
            </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>        
    </div>


{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ property.title }} {% endblock %}


{% block body %}
    <div class="container-fluid py-5 mb-4 bg-light">

        {% for msg in app.flashes('success') %}
            <div class="alert alert-success">{{ msg }}</div>
        {% endfor %}

        {% if not form.vars.valid %}
            <div class="alert alert-danger">Erreur : je ne sais pas trop dire ...</div>
        {% endif %}
        
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                {% if property.filename %}
                    <!--<img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" class="card-img-top" style="width: 100%; height: auto">-->
                    {% include "property/_carousel.html.twig" %}

                {% else %}
                    <img src="{{ '/images/properties/empty.jpg' | imagine_filter('medium') }}" class="card-img-top" style="width: 100%; height: auto">        
                {% endif %}

                </div>            
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-weight: bold; font-size: 4rem">{{ property.formattedPrice }} €</div>
                    <a href="#" class="btn btn-primary" id="contactButton"{% if form.vars.submitted %} style="display: none;" {% endif %}>Contacter l'agence</a>
                    <div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
                        {{ form_start(form) }}

                        <div class="row g-3 align-items-end">
                            <div class="col mt-4">{{ form_row(form.firstname) }} </div>
                            <div class="col mt-4">{{ form_row(form.lastname) }} </div>
                        </div>                    
                        <div class="row g-3 align-items-end">
                            <div class="col mt-4">{{ form_row(form.phone) }} </div>
                            <div class="col mt-4">{{ form_row(form.email) }} </div>
                        </div>                    
                                            
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button class="btn btn-primary mt-4">Envoyer</btn>
                        </div>
                        {{ form_end(form) }}
                    </div>                   
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heattype }}</td>
                    </tr>                
                </table>
            </div>            
            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item"> {{ option.name }} </li>
                    {% endfor %}
                </ul>
            </div>  
        </div>          
    </div>    
{% endblock %}